/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestmentIdeasRouteImport } from './routes/investment-ideas'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WatchlistsRouteImport } from './routes/watchlists'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentIdeasRoute = InvestmentIdeasRouteImport.update({
  id: '/investment-ideas',
  path: '/investment-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistsRoute = WatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/investment-ideas': typeof InvestmentIdeasRoute
  '/settings': typeof SettingsRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/investment-ideas': typeof InvestmentIdeasRoute
  '/settings': typeof SettingsRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/investment-ideas': typeof InvestmentIdeasRoute
  '/settings': typeof SettingsRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/investment-ideas' | '/settings' | '/watchlists'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/investment-ideas' | '/settings' | '/watchlists'
  id: '__root__' | '/' | '/investment-ideas' | '/settings' | '/watchlists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvestmentIdeasRoute: typeof InvestmentIdeasRoute
  SettingsRoute: typeof SettingsRoute
  WatchlistsRoute: typeof WatchlistsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-ideas': {
      id: '/investment-ideas'
      path: '/investment-ideas'
      fullPath: '/investment-ideas'
      preLoaderRoute: typeof InvestmentIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlists': {
      id: '/watchlists'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof WatchlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvestmentIdeasRoute: InvestmentIdeasRoute,
  SettingsRoute: SettingsRoute,
  WatchlistsRoute: WatchlistsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
